
// ========== Script 1 ==========
window['ppConfig'] = {productName: 'AlphaFoldUi', deleteIsEnforced:  true , sealIsEnforced:  true , heartbeatRate:  0.5 , periodicReportingRateMillis:  60000.0 , disableAllReporting:  false };(function(){'use strict';function k(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function l(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:k(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var m=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function n(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=n(this);function q(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&m(c,a,{configurable:!0,writable:!0,value:b})}}
q("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
q("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});function r(a,b,c){a("https://csp.withgoogle.com/csp/proto/"+encodeURIComponent(b),JSON.stringify(c))}function t(){var a;if((a=window.ppConfig)==null?0:a.disableAllReporting)return function(){};var b,c,d,e;return(e=(b=window)==null?void 0:(c=b.navigator)==null?void 0:(d=c.sendBeacon)==null?void 0:d.bind(navigator))!=null?e:u}function u(a,b){var c=new XMLHttpRequest;c.open("POST",a);c.send(b)}
function v(){var a=(w=Object.prototype)==null?void 0:w.__lookupGetter__("__proto__"),b=x,c=y;return function(){var d=a.call(this),e,f,g,h;r(c,b,{type:"ACCESS_GET",origin:(f=window.location.origin)!=null?f:"unknown",report:{className:(g=d==null?void 0:(e=d.constructor)==null?void 0:e.name)!=null?g:"unknown",stackTrace:(h=Error().stack)!=null?h:"unknown"}});return d}}
function z(){var a=(A=Object.prototype)==null?void 0:A.__lookupSetter__("__proto__"),b=x,c=y;return function(d){d=a.call(this,d);var e,f,g,h;r(c,b,{type:"ACCESS_SET",origin:(f=window.location.origin)!=null?f:"unknown",report:{className:(g=d==null?void 0:(e=d.constructor)==null?void 0:e.name)!=null?g:"unknown",stackTrace:(h=Error().stack)!=null?h:"unknown"}});return d}}function B(a,b){C(a.productName,b);setInterval(function(){C(a.productName,b)},a.periodicReportingRateMillis)}
var D="constructor __defineGetter__ __defineSetter__ hasOwnProperty __lookupGetter__ __lookupSetter__ isPrototypeOf propertyIsEnumerable toString valueOf __proto__ toLocaleString x_ngfn_x".split(" "),E=D.concat,F=navigator.userAgent.match(/Firefox\/([0-9]+)\./),G=(!F||F.length<2?0:Number(F[1])<75)?["toSource"]:[],H;if(G instanceof Array)H=G;else{for(var I=l(G),J,K=[];!(J=I.next()).done;)K.push(J.value);H=K}var L=E.call(D,H),M=[];
function C(a,b){for(var c=[],d=l(Object.getOwnPropertyNames(Object.prototype)),e=d.next();!e.done;e=d.next())e=e.value,L.includes(e)||M.includes(e)||c.push(e);e=Object.prototype;d=[];for(var f=0;f<c.length;f++){var g=c[f];d[f]={name:g,descriptor:Object.getOwnPropertyDescriptor(Object.prototype,g),type:typeof e[g]}}if(d.length!==0){c=l(d);for(e=c.next();!e.done;e=c.next())M.push(e.value.name);var h;r(b,a,{type:"SEAL",origin:(h=window.location.origin)!=null?h:"unknown",report:{blockers:d}})}};var N=Math.random(),O=t(),P=window.ppConfig;P&&(P.disableAllReporting||P.deleteIsEnforced&&P.sealIsEnforced||N<P.heartbeatRate&&r(O,P.productName,{origin:window.location.origin,type:"HEARTBEAT"}));var y=t(),Q=window.ppConfig;if(Q)if(Q.deleteIsEnforced)delete Object.prototype.__proto__;else if(!Q.disableAllReporting){var x=Q.productName;try{var w,A;Object.defineProperty(Object.prototype,"__proto__",{enumerable:!1,get:v(),set:z()})}catch(a){}}
(function(){var a=t(),b=window.ppConfig;b&&(b.sealIsEnforced?Object.seal(Object.prototype):b.disableAllReporting||(document.readyState!=="loading"?B(b,a):document.addEventListener("DOMContentLoaded",function(){B(b,a)})))})();}).call(this);


// ========== Script 2 ==========
window.WIZ_global_data = {"AfY8Hf":true,"DpimGf":false,"EP1ykd":["/_/*","/accounts/*","/dummy"],"FdrFJe":"3386306357538622855","HiPsbb":1,"Im6cmf":"/_/AlphaFoldUi","LoQv7e":false,"MT7f9b":[],"MUE6Ne":"AlphaFoldUi","QrtxK":"","S06Grb":"","S6lZl":95925410,"TSDtV":"%.@.[[null,[[45646744,null,true,null,null,null,\"tuvEVe\"],[45677661,null,null,null,\"20250804-291e4da1-9759-4ec8-afd8-9f511d3f211b\",null,\"MZxbi\"],[45614424,null,true,null,null,null,\"n7LJKc\"],[45681345,null,null,null,\"2025-02-03\",null,\"hfgIR\"],[45689800,null,true,null,null,null,\"hXDQnf\"],[45693056,null,false,null,null,null,\"J7qa4d\"],[45530989,null,null,null,\"examplefold_pdb_7x14\",null,\"iKWepb\"],[45678395,null,null,null,\"20250205-59521836-60cb-4b16-9b31-1d8a993487cc\",null,\"qdGbWe\"],[45724424,null,false,null,null,null,\"XptFWe\"],[45530981,null,null,null,\"examplefold_pdb_1aay\",null,\"vWWr6\"],[45618956,null,null,null,\"https://accounts.google.com\",null,\"IgxnKd\"],[45683929,null,null,null,\"762474226\",null,\"wCPWUe\"],[45700107,null,true,null,null,null,\"Oa6qvb\"],[45683924,null,true,null,null,null,\"HXy1Yd\"],[45613785,null,true,null,null,null,\"A3gBcd\"],[45614275,null,false,null,null,null,\"yHWsme\"],[45613786,null,false,null,null,null,\"ZNVmee\"],[45692003,null,false,null,null,null,\"GzLgzb\"],[45646743,null,false,null,null,null,\"a3URPd\"],[45659865,null,null,null,\"1FAIpQLSe_WEk7iUc1ALOP3Db-uRD2TJcppeY9M9eVIccP_B3xUMdfhA\",null,\"Locpy\"],[45689703,null,true,null,null,null,\"lVckS\"],[45427877,null,true,null,null,null,\"ZxDSlf\"],[45672509,null,true,null,null,null,\"pNstGd\"],[45649065,null,true,null,null,null,\"uQmZjc\"],[45666436,null,false,null,null,null,\"fgsvCc\"],[45683463,null,null,null,\"2021-09-30\",null,\"JaC6zf\"],[45678394,null,null,null,\"20250731-1afb97eb-c6f4-43e7-a075-56edcd14c4ab\",null,\"l5hhof\"],[45429220,null,null,null,\"https://alphafold.ebi.ac.uk/files/AF-Q8W3K0-F1-model_v4.cif\",null,\"Oai95c\"],[45649064,null,true,null,null,null,\"JAyyH\"],[45664143,null,false,null,null,null,\"tPkJed\"],[45706367,null,false,null,null,null,\"UEoBGc\"],[45679944,null,true,null,null,null,\"ui4od\"],[45614423,null,true,null,null,null,\"Qe2tY\"],[45530988,null,null,null,\"examplefold_pdb_5sjh\",null,\"wazwse\"],[45731691,null,false,null,null,null,\"pTAxmb\"],[45622073,null,true,null,null,null,\"ZGEFkb\"],[45430310,5318072,null,null,null,null,\"oKrHCf\"],[45633822,null,true,null,null,null,\"hFOMHc\"],[45545541,null,true,null,null,null,\"LxXbLc\"]],\"CAMSBx0C8eCyNQg\\u003d\"]]]","UUFaWc":"%.@.null,1000,2]","Vvafkd":false,"b5W2zf":"default_AlphaFoldUi","cfb2h":"boq_deepmind-alphafoldserver-web_20260118.01_p0","eptZe":"/_/AlphaFoldUi/","fPDxwd":[105739270],"gGcLoe":false,"hsFLT":"%.@.null,1000,2]","iCzhFc":false,"mXaIFf":true,"nQyAE":{},"p9hQne":"https://www.gstatic.com/_/boq-deepmind-alphafold-server/_/r/","qwAQke":"AlphaFoldUi","rtQCxc":-480,"u4g7r":"%.@.null,1,2]","vJQk6":false,"xnI9P":true,"xwAfE":true,"y2FhP":"prod","yFnxrf":1957,"zChJod":"%.@.]"};

// ========== Script 5 ==========
var _F_cssRowKey = 'boq-deepmind-alphafold-server.AlphaFoldUi.74VhPKmNEeU.L.X.O';var _F_combinedSignature = 'AGFH4YndaRfQfzS59eYlTCXLHLTJVySeVQ';function _DumpException(e) {throw e;}

// ========== Script 6 ==========
var AF_initDataKeys = []; var AF_dataServiceRequests = {}; var AF_initDataChunkQueue = []; var AF_initDataCallback; var AF_initDataInitializeCallback; if (AF_initDataInitializeCallback) {AF_initDataInitializeCallback(AF_initDataKeys, AF_initDataChunkQueue, AF_dataServiceRequests);}if (!AF_initDataCallback) {AF_initDataCallback = function(chunk) {AF_initDataChunkQueue.push(chunk);};}
